
# Appraoch
TWO_POINTER = None
PREFIX_SUM = None
SLIDING_WINDOW = None
GREEDY = None
DIVIDE_AND_CONQUER = None
DESIGN = None

# Platform
GRIND_75 = None

# Data Structure
ARRAY = None
STRING = None
SET = None
TREE = None
BINARY_TREE = None
LINKED_LIST = None
DOUBLY_LINKED_LIST = None
STACK = None
QUEUE = None
HEAP = None
GRAPH = None
HASHMAP = None
MATRIX = None

# Design Pattern
CREATIONAL_FACTORY = None
STRUCTURAL = None
BEHAVIORAL_OBSERVER = None

# Problem Type
RECURSION = None
BINARY_SEARCH = None
BFS = None
DFS = None
DYNAMIC_PROGRAMMING = None